server:
  port: 9527


spring:
  application:
    name: cloud-gateway-service
  cloud:
    gateway:
      routes:
        - id: payment_routh1  # 路由器id，没有固定规则 但要求唯一 ，建议配合服务名
          uri: http://localhost:8001  #匹配后提供的服务路由器地址
          predicates:                #断言，路径相匹配进行路由
            - Path=/payment/get/**




        - id: payment_routh2
          uri: http://localhost:8001
          predicates:
              - Path=/payment/lb/**



eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka