server:
  port: 80

spring:
  application:
    name: cloud-consumer-feign-order
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka




ribbon:
  ReadTimeout: 5000     #不知道为啥 这俩属性点不出来 一直报黄，但是可以正常使用
  ConnectTimeout: 5000



logging:
  level:
    com.atguigu.springcloud.service.PaymentService: debug