server:
  port: 8006

spring:
  application:
    name: cloud-provider-payment-8006
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}