server:
  port: 8002



spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource  #当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver   #mysql驱动包
    url: jdbc:mysql://192.168.3.10:3306/db2019?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

#    druid:
#      filters: stat
#      initial-size: 2
#      max-active: 300
#      max-wait: 6000
#      time-between-eviction-runs-millis: 60000
#      min-evictable-idle-time-millis: 30000
#      validation-query: select 1
#      test-while-idle: true
#      test-on-borrow: false
#      test-on-return: false
#      pool-prepared-statements: false
#      max-pool-prepared-statement-per-connection-size: 200



mybatis:
  mapperlocations: classpath:mapper/*.xml
  type-aliases-package: com.atguigu.springcloud.entities
#所有Entity别名类所在包



eureka:
  client:
    # eureka 的注册地址
    service-url:
      # 默认地址是这个
      #defaultZone: http://localhost:7001/eureka/
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
      #是否注册到eureka 中
    register-with-eureka: true
    # 是否允许自己抓取注册信息
    fetch-registry: true
  instance:
    instance-id: payment8002    # 在eureka 中可以直接显示项目名称
    prefer-ip-address: true     #再eureka 中，鼠标指向对应的服务可以在状态栏展示ip地址
