server:
  port: 80

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka

spring:
  application:
    name: cloud-consumer-feign-hyxtrix-order80